CC = gcc
CFLAGS = -Wall -Wextra -O2

all: q1 q2 q3 q4

q1: q1.c
	$(CC) $(CFLAGS) -o q1 q1.c
q2: q2.c
	$(CC) $(CFLAGS) -o q2 q2.c
q3: q3.c
	$(CC) $(CFLAGS) -o q3 q3.c
q4: q4.c
	$(CC) $(CFLAGS) -o q4 q4.c

clean:
	rm -f q1 q2 q3 q4